### ISSUE TITLE
Unexpected type issue when starting PyHI

### ISSUE THREAD

**Issue by zruan** [xuewuzhang-UTSW/PyHI#1]
Hi Dr Zhang,

I was trying to use the PyHI to index a helical filament from 2D. However, the following error appears when I tried to run `python3 PyHI_v004.py`

> (PyHI) Zheng.Ruan@C02D47YVMD6M ~/software/PyHI % python PyHI_v004.py 
> Traceback (most recent call last):
>   File "/Users/Zheng.Ruan/software/PyHI/PyHI_v004.py", line 1925, in <module>
>     main()
>   File "/Users/Zheng.Ruan/software/PyHI/PyHI_v004.py", line 1920, in main
>     gui = MainWindow()
>   File "/Users/Zheng.Ruan/software/PyHI/PyHI_v004.py", line 71, in __init__
>     self.overall_layout()
>   File "/Users/Zheng.Ruan/software/PyHI/PyHI_v004.py", line 162, in overall_layout
>     self.tab1_ctrl_left_column()
>   File "/Users/Zheng.Ruan/software/PyHI/PyHI_v004.py", line 235, in tab1_ctrl_left_column
>     self.minSigma_chooser.setMinimum(-30.5)
> TypeError: setMinimum(self, int): argument 1 has unexpected type 'float'

The PyQt5 version that I used is 5.15.2 from pip.

Best,
Zheng

**Comment by xuewuzhang-UTSW** [comment]
Hi Zheng,
I just uploaded a slightly modified version. Can you please try it and let me know if it solves the problem?
Thanks,
Xuewu

**Comment by zruan** [comment]
Thank you for the prompt response. Yes, it is working now.

**Comment by xuewuzhang-UTSW** [comment]
This issue has been resolved with the new version.
