### ISSUE TITLE
Average_power_spec_calc_v03.py

### ISSUE THREAD

**Issue by lorago92** [xuewuzhang-UTSW/PyHI#2]
Hello, 
I'm running Average_power_spec_calc_v03.py but I get the following message

Traceback (most recent call last):
File "Average_power_spec_calc_v03.py", line 84, in <module>
         fft_average=fft_stack/process_count
ZeroDivisionErrorr: division by zero 

I am using a particles.star file as input (from Class2D/Select/ job in relion 3.1) so I don't get the problem here. 

Cheers 
Lorenzo

**Comment by xuewuzhang-UTSW** [comment]
Hi Lorenzo,
Based on the error message, it seems like that the script did not successfully get the "process_count" (the number of particles to be processed) from your input files, hence the "division by zero" problem. This suggest that it did not find the particle stack files (.mrcs). Are you running the script in the directory where the "particles.star" file is? Can you paste the command you used?
Thanks,
Xuewu

**Comment by lorago92** [comment]
Here the command:

python Average_power_spec_calc_v03.py -i /data/MizunoLab/agostinil2/NIHCryoem/singleparticle/Processing/3E/Select/job112/particles.star -d /data/MizunoLab/agostinil2/NIHCryoem/singleparticle/Processing/3E/Select/job112

No, I am actually running the job from another directory. Should I run it from the relion folder?

**Comment by xuewuzhang-UTSW** [comment]
I see what's the issue: your command after the "-d" does not point to the correct directory to the ".mrcs" particle stack directory, instead it points to the "Select/job112" directory (which only has the 2D class images, not the actual particles). The particle stacks should be under one of your "Extract" jobs (whichever one you used for your 2D class run).  You can find exactly where that directory is in your "particles.star" file. After the header of the file, you should see that each line represents data for one particle. Look for something like "00007@Extract/job033/Movies/XXXX.mrcs".
Xuewu

**Comment by lorago92** [comment]
It runs now. Thank you. 
Lorenzo
