### ISSUE TITLE
Need to load image and set sensible LL distance first!

### ISSUE THREAD

**Issue by msleutel** [xuewuzhang-UTSW/PyHI#3]
Hello,

I'm trying to run PyHI_v004.py. The GUI starts up with no problems, and I can load my 2D class averages (.mrc) that were generated in CryoSparc v 4.2.1. The classes are displayed, as well as the calculated power spectrum. However, when I try to "Set LL dist" I get the following error message: 

"Need to load image and set sensible LL distance first!"

Could you please advise ?

Best,

Mike Sleutel

**Comment by xuewuzhang-UTSW** [comment]
Can you please update your matplotlib to a newer version and try again?

**Comment by xuewuzhang-UTSW** [comment]
The issue is caused by using an older version of matplotlib (3.2). Updating to a newer version should fix it.
